components/VotesTable/VotesTableRow.tsx
helpers/getVoteMetaData.ts
public/assets/icons/rolled.svg
stories/mocks/votes.ts
types/global.ts

We have a function that gets transaction hashes for votes from the chain. When there is no transaction hash available, we know that particular vote was rolled. Add an indicator in the UI that shows when a vote was rolled.
* Add an `isRolled` property to vote metadata
* Add a "rolled" indicator to the votes in the votes table

feat: show vote rolled

---

components/Panel/StakeUnstakePanel/Stake.tsx

There was an issue where staking multiple times wihtout wiating for previous transactions to go through would cause transactions to revert. this was because approvals were only set for the stake amount.  this sets unlimited approvals to prevent those reverts and prevent user from needing to re-approve.

fix: use max approval when setting stake

---

.gitignore
components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
components/Panel/StakeUnstakePanel/Unstake.tsx
constants/queryKeys.ts
contexts/BalancesContext.tsx
helpers/getCanUnstakeTime.ts
hooks/index.ts
hooks/queries/balances/useUnstakeCoolDown.ts
web3/index.ts
web3/queries/balances/getStakerDetails.ts
web3/queries/balances/getUnstakeCoolDown.ts

This fetches the cooldown time from the contract and updates relevant places in code to reflect time.

fix: dynamically fetch unstake time from contract, update copy

---

components/Panel/StakeUnstakePanel/CooldownTimer.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
components/Panel/StakeUnstakePanel/Unstake.tsx
hooks/mutations/balances/useRequestUnstake.ts

claim button was previously hidden when you had tokens to claim
this enables the button and lets user know why they cant unstake more if they have unclaimed tokens

fix: claim button now visible

---

hooks/mutations/balances/useExecuteUnstake.ts

Looks like there is a bit of a race condition when doing this subtraction. When unstaking we somtimes see an negative value, this is due to the state of staked balance changing before we do the subtraction.  we just make sure here to only show 0 if the number goes negative.

fix: dont let staking balance go below 0

---

components/HowItWorks/HowItWorks.tsx

We should be including any pending unstake amount in the total balance

fix: include pending unstake in total balance

---

components/Button/Button.tsx
components/Nav/Nav.tsx
helpers/index.ts
helpers/misc.ts

Takes external link detection, puts it as a utility and uses it in a link button. This should fix the issue, but I wasnt able to identify the particular local in the bug report.

fix: have button links detect when to open new tab

---

components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
helpers/ethers.ts
helpers/index.ts

This adds a second ether parsing function which catches an error and returns 0. A better but more work solution would be to validate user input before passing it to be parsed, but I don't think the extra work is justified, as this should work fine.

fix: catch ether parsing errors from user input

---

components/PanelErrorBanner/PanelErrorBanner.tsx
helpers/ethers.ts
helpers/index.ts
helpers/initOnboard.ts
helpers/misc.ts
hooks/helpers/useHandleError.ts
hooks/mutations/balances/useApprove.ts
hooks/mutations/balances/useExecuteUnstake.ts
hooks/mutations/balances/useRequestUnstake.ts
hooks/mutations/balances/useStake.ts
hooks/mutations/balances/useWithdrawAndRestake.ts
hooks/mutations/balances/useWithdrawRewards.ts

Transaction errors now get formatted to only include the message part. previously it would include call data.
This may not cover all transactions, so please comment if there needs to be more covered.

fix: format ethers tx errors for user

---

components/ErrorBanner/ErrorBanner.tsx
components/Panel/Panel.tsx
components/PanelErrorBanner/PanelErrorBanner.tsx
public/assets/icons/close.svg

This adds an X to close error messages

feat: add close button to main errors

---

components/VotesTable/VotesTableRow.tsx
contexts/VotesContext.tsx
hooks/mutations/votes/useCommitVotes.ts
hooks/mutations/votes/useRevealVotes.ts
stories/mocks/votes.ts
types/user.ts
types/voting.ts
web3/queries/votes/getCommittedVotes.ts
web3/queries/votes/getRevealedVotes.ts
yarn.lock

This adds transaction hash to the reveal/commit data when we get that data for the user. this is used to create a clickable button to go to etherscan when those exist. 
this is now a link:

feat: add transaction links to commit reveal txs

---

components/Panel/HistoryPanel.tsx
components/Panel/PanelTitle.tsx
components/Panel/VotePanel/VotePanel.tsx
components/VoteHistoryTable/VoteHistoryTableRow.tsx
components/VotesTable/VotesTableRow.tsx
constant/index.ts
constant/query/graphEndpoint.ts
graph/index.ts
graph/queries/getPastVotes.ts
helpers/voting/getVoteMetaData.ts
helpers/voting/makePriceRequestsByKey.ts
hooks/queries/votes/usePastVotes.ts
stories/mocks/votes.ts
types/voting.ts
web3/queries/votes/getVoteTransactionHashes.ts

This adds votes from a previous contract to our past-votes page. It requires a new env variable to point to the v1 voting contractact : NEXT_PUBLIC_GRAPH_ENDPOINT_V1.

feat: add votes from prev contract to vote history

---

helpers/voting/makePriceRequestsByKey.ts

Decoding hex strings can throw when the input data is malformed. Add try/catch logic that adds warnings in that case.

improve: handle malformed ancillary data

---

components/LoadingSkeleton/LoadingSkeleton.tsx
components/VotesList/VotesListItem.tsx

I had some unnecessary logic in the loading skeleton that caused a bug where the previous content of the loading skeleton would show through underneath the loader. 
* Simplify the loading skeleton placeholder logic which also fixes the bug

bug: loading skeleton placeholder

---

components/Input/AmountInput.tsx
components/Input/TextInput.tsx
components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
constant/index.ts
constant/misc/maximumApprovalAmountString.ts
helpers/index.ts
helpers/web3/ethers.ts
hooks/helpers/useHandleDecimalInput.ts
hooks/index.ts
web3/mutations/staking/approve.ts

When clicking "max" in the approve input, we use the largest allowed uint256 as the value (essentially the same as approving an unlimited amount). However, this shows a very large number in the input which is ugly and confusing to the user.
* Add a string value for "unlimited approval" and show that in the input instead
* Handle this string as a possible input for the approve mutation

bug: maximum approve shows huge number that overflows input

---

components/VotesList/VotesListItem.tsx

When the user chooses a custom input for a request that has a dropdown, we must check if this is the case when finding their existing vote. Otherwise we will just show the dropdown and it will look like the user did not input a vote.
* Check if the user added a custom input, and show a text input with that value instead of the dropdown if that is the case.

improve: handle existing custom input

---

components/VotesList/VotesListItem.tsx

The logic for detecting custom votes will always return true when the decrypted vote does not exist.
* Check that the decrypted vote exists when detecting a custom vote

bug: check if vote exists before setting is custom

---

components/VotesList/VotesListItem.tsx

Using a button for the vote status link makes the link red which gives the impression that something is wrong. Rather use a link that's styled to look like a link, its also clearer that its a link to the user.

improve: use link instead of button for vote status

---

components/VotesList/VotesListItem.tsx

Include a formatted date and time in each of the votes in the votes list.

improve: add date and time to votes

---

graph/queries/getPastVotes.ts
types/queries.ts

For reasons I cannot remember, I decided to use the internal graphql id for votes to get the identifiers of past votes. This makes no sense because we literally already get the actual value from the graph, and also because it introduced a bug where we split the internal identifier string which doesn't work consistently.
* Remove the query for the internal ID
* Use the identifier returned from the graph as-is

bug: should show across v2 as identifier

---

pages/api/augment-request.ts
pages/api/warm-cache.ts

This PR adds a serverless function endpoint used to warm the other heavy endpoints to speed up the cache of heavy operations. Vercel will cache the responces for a given request for 30 days. therefor we simply need to run this endpoint once after deployment and the cache will be built and be fast!

feat: update request augmentation and add cache warming endpoint

---

components/Panel/Panel.tsx

Make sure that the panel is always scrolled to the top whenever the user opens the panel.

improve: scroll panel to top on open

---

components/Panel/HistoryPanel.tsx
components/Votes/Votes.tsx
components/pages/PastVotes.tsx
components/pages/UpcomingVotes.tsx
constant/index.ts
constant/misc/defaultResultsPerPage.ts
contexts/PaginationContext.tsx

Increase the default number of results per page in paginated data from 10 to 20.

improve: increase default pagination results per page

---

components/Banner/Banner.tsx
components/ErrorBanner/ErrorBanner.tsx
components/GlobalStyle/GlobalStyle.ts
components/Header/Header.tsx
components/HowItWorks/HowItWorks.tsx
components/pages/styles.tsx

Slight alignment change in the error banner as requested by Jesper.

improve: left align text in error banner

---

components/Panel/ClaimPanel.tsx

The rewards ticker in the claim panel was shifting around weirdly as the number ticks up. I added css to prevent the line from wrapping over when the number gets bigger which fixes the issue.

bug: add whitespace nowrap to rewards

---

components/Panel/ClaimPanel.tsx
components/Panel/MenuPanel/MenuPanel.tsx
components/Panel/PanelTitle.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx

It's really satisfying when things line up perfectly.

improve: add min heights to panel titles

---

pages/api/_common.ts
pages/api/augment-request.ts
pages/api/decode-admin.ts
pages/api/past-rewards.ts
pages/api/warm-cache.ts

This PR adds the ability for the `past-rewards` serverless function to include the total amount of rewards fetched. It also includes a small formatting improvement.

feat: add total rewards fetched

---

components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
components/Panel/StakeUnstakePanel/Unstake.tsx
constant/query/queryKeys.ts
contexts/StakingContext.tsx
helpers/staking/getCanUnstakeTime.ts
hooks/index.ts
hooks/mutations/staking/useExecuteUnstake.ts
hooks/mutations/staking/useRequestUnstake.ts
hooks/mutations/staking/useStake.ts
hooks/mutations/staking/useWithdrawAndRestake.ts
hooks/mutations/staking/useWithdrawRewards.ts
hooks/queries/staking/useStakedBalance.ts
hooks/queries/staking/useStakerDetails.ts
hooks/queries/staking/useUnstakeCoolDown.ts
types/staking.ts
web3/index.ts
web3/queries/staking/getStakedBalance.ts
web3/queries/staking/getStakerDetails.ts
web3/queries/staking/getUnstakeCoolDown.ts

There was some trouble with the max button for staking / unstaking. Fix these issues by getting the staked balance by calling `getVoterStakePostUpdate()` to make sure its accurate, and also add some guard logic to make sure that we never attempt to stake / unstake more than the staked / unstaked balance when using the max button.

fix: unstaking max button sets an amount higher than staked balance

---

components/Panel/Panel.tsx
contexts/PanelContext.tsx
package.json
types/ui.ts
yarn.lock

We want the side panel to always open with its content scrolled all the way to the top. This proved to be impossible with the [reach ui dialog library](https://reach.tech/dialog/) we were using because that library destroys and recreates the dom node of the panel's content. this means that we cannot access a ref to the content to perform a scroll action until _after_ the component is fully rendered, causing the scroll to happen after the panel slides in which looks ugly.
I've been getting quite frustrated with the inflexibility of the reach ui component for a while now. So I've decided to remove that lib and replace it with my own implementation. It turns out that the reach component doesn't actually do all that much, and I was able to address all of the [accessibility …

fix: panel scroll issue is back

---

components/Panel/VotePanel/Result.tsx
helpers/util/formatNumber.ts

Decimals used to go on forever, now all are set to 2:

improve: truncate past votes numbers to 2 decimals

---

components/Panel/VotePanel/Details.tsx

We already have the correct value from the contract, so use that instead of getting a millisecond timestamp from the time as date.

fix: use time from contract in vote details panel

---

constant/web3/addresses.ts
contexts/ContractsContext.tsx
helpers/web3/wallet.ts
hooks/queries/votes/useEncryptedVotes.ts
web3/contracts/createVotingV1ContractInstance.ts
web3/index.ts
web3/queries/votes/getEncryptedVotes.ts

There were some logical issues with how we fetched encrypted votes from the chain. Firstly, we were not using a checksum address, which caused ethers to think the address was incorrect (I could swear this worked before though so this is quite strange). Secondly, we were only fetching encrypted votes for the current round, which meant that we would not have encrypted votes for past votes. I fixed these problems, and also added another event query to fetch the encrypted votes from v1 as well — now you will see your vote in the past votes from v1 too.
* use checksum address in user context to prevent missed event queries
* get encrypted votes for all rounds to show in past votes
* get encrypted votes from v1 in the same query

fix: past votes shows me that i did not vote

---

web3/mutations/votes/commitVotes.ts
web3/mutations/votes/revealVotes.ts

When we are only committing or revealing one vote, we should rather call the commit or reveal contract methods directly instead of using multicall.

fix: no multicall on single vote

---

components/Panel/ClaimPanel.tsx

Claim button was not being disabled when there wasnt anything to claim. This was tricky because technically there is a non 0 amount to claim, but it shows up in the UI as 0 because of truncation. We set a minimum value as a threshold of ".01" to claiming to make UI consistent with button behavior.

fix: disable claiming with amounts below threshold

---

components/HowItWorks/HowItWorks.tsx

Changing the phrasing of this sentence fixes the issue of jumpy looking text in the rewards counter. I think that this phrasing would look better anyway regardless of the bug. It's visually pleasing to have the emphasis at the end of the text.

improve: rearrange words in unclaimed rewards

---

components/Panel/HistoryPanel.tsx
contexts/VotesContext.tsx

This basically just filters out v1 votes from history panel.

fix: filter v1 votes from history panel

---

components/Panel/VotePanel/Result.tsx

Adding `aspect-ratio: 1/1` forces the element to always have the same width and height, which in turn makes sure that it's always circular in this case.

fix: add aspect ratio to vote result key dot

---

components/Tabs/Tabs.tsx
components/Tabs/index.ts
package.json
yarn.lock

Reach UI was the go-to accessible react component library for the last several years. Unfortunately, it is [no longer actively maintained](https://github.com/reach/reach-ui/issues/972).
It's not critical that we replace all our dependencies on their components right away, but I've been taking the opportunity to swap out reach ui for alternatives when I encounter bugs in those components (like in the `Panel` component for example).
In this case, the `Tabs` used in the panel for the vote results and vote details had an issue where it would set `cursor: pointer` on all of its children even though those children were not interactive — hence the bug reported where the chart shows a hand cursor when it is not interactive.
I do intend to add interactivity in the future, but for now I just wanted …

fix: replace reach tabs lib with radix tabs lib

---

components/Panel/Panel.tsx

Signed-off-by: ryanwolhuter <dev@ryanwolhuter.com>

fix: add z index so loading skeletons do not render on top of the panel

---

.storybook/preview.tsx
contexts/PaginationContext.tsx

[Updating nested objects in react state](https://beta.reactjs.org/learn/updating-objects-in-state) is ugly. Trying to maintain an object of objects for the various pagination states was a mistake — it didn't work properly to begin with, and to make it work, we'd have to use multiple layers of object spreads all over the place.
Much easier and cleaner to just use separate state for each object.

fix: paginating one page also paginates the other pages

---

hooks/queries/votes/useAugmentedVoteData.ts
hooks/queries/votes/useDecodedAdminTransactions.ts

The app still works fine without decoded admin data and augmented vote data — they are enhancements. In the event that something goes wrong with them (in the serverless functions) we don't want to make the user think that the _whole_ app is broken by showing a "error fetching vote data" error.

improve: remove error handlers from non-critical data fetchers

---

components/Wallet/Wallet.tsx

This will clear any contracts which have a previous signer in it. this may help prevent the problem where we can possibly submit a transaction based on another wallet account.

fix: ensure we clear contracts with signers when it changes

---

components/Votes/Votes.tsx
components/Wallet/Wallet.tsx
contexts/UserContext.tsx
contexts/WalletContext.tsx
helpers/index.ts
helpers/voting/formatVotes.ts
helpers/web3/signing.ts
hooks/helpers/useSign.ts
hooks/index.ts
hooks/queries/votes/useDecryptedVotes.ts
pages/_app.tsx

When first opening the page metamask immediately asks us to sign a message. If this message is cancelled by the user, theres no clear way to re-sign without reloading the page. Would notice that multiple signature requests would be sent to users metamask. Additionally commit/reveal were not disabled if the user had not signed.
This gives you an explicit button to "sign"  with a tooltip before you can commit or reveal. We also refactor our button display logic to help make this more managable. 
to test this new flow, you must clear your application cache.

improve: add explicit signing button

---

components/Notifications/Notification.tsx
components/Panel/DelegationPanel.tsx
components/Panel/MenuPanel/MenuPanel.tsx
components/Panel/VotePanel/Details.tsx
components/VotesList/VotesListItem.tsx
components/Wallet/Wallet.tsx
components/pages/WalletSettings/PendingRequests.tsx
constant/misc/errorMessages.ts
graph/queries/getPastVotes.ts
graph/queries/getUserVotingAndStakingDetails.ts
helpers/config.ts
helpers/util/misc.ts
helpers/web3/initOnboard.ts
web3/contracts/createVotingContractInstance.ts
web3/contracts/createVotingTokenContractInstance.ts
web3/contracts/createVotingV1ContractInstance.ts
web3/mutations/staking/approve.ts
web3/queries/staking/getTokenAllowance.ts
web3/queries/votes/getUpcomingVotes.ts

we need to remove references to goerli from the app in order to prepare it to run on mainnet. 
this generalizes the app configuration, combines constants we need for each chain and selects it based on chain id specified in env.  i've tried to identify places in the app that were hard coded to goerli and replaced them with the generalized configuration. 
This requires changes to vercels envs before this will run by removing references to goerli.  It also requires a new var that specifies the chain id the app is on.

improve: remove references to goerli, allow path to add chains

---

components/Wallet/Wallet.tsx

Changes connect button to use primary colors ( previously gray)

fix: change connect button to primary colors

---

components/Panel/VotePanel/ChainIcon.tsx

This prevents crashing by explicitly checking that icon and chain name exists

fix: fix crashing in chainicon

---

components/Votes/Votes.tsx
components/Wallet/Wallet.tsx
contexts/UserContext.tsx
contexts/WalletContext.tsx

Commit/reveal button was not being disabled when user was on wrong chain. 
This changes the commit/reveal button behavior to allow the user to switch to the correct chain. 
This also removes the automatic behavior of immediately requesting metamask to switch chain, instead preferring the user explicitly click the button.
This is a slight issue becuase this button is hidden unlesss there is an active vote. will talk to jesper to see how we can resolve.

feat: add network switch button

---

components/Panel/StakeUnstakePanel/Stake.tsx
helpers/web3/ethers.ts

we were allowing people to try to stake more than they had unstaked, causing revert
we check the unstaked balance, we also had to change how we were parsing eth because the number cast caused a mismatch in the compared result.

fix: check user unstaked balance before staking

---

components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
components/Panel/VotePanel/VotePanel.tsx
components/Tabs/Tabs.tsx

there seems to be an intermittent issue where panel tabs do not show sometimes. 
not sure if this fixes it, but we can set an optional default tab when the panel is opened. this is using a react tab library and the component is currently uncontrolled, so perhaps setting a default when opened fixes this.

fix: set default tab for stake/unstake panel

---

components/Panel/VotePanel/Discussion.tsx
hooks/index.ts
hooks/queries/discord/useDiscordThread.ts
next.config.js
pages/api/discord-thread.ts
types/voting.ts
web3/index.ts
web3/queries/discord/getDiscordThread.ts

We had independently built a discussion panel for votes, and a discord serverless api.  We needed to wire these together to get discussions working correctly.
This changes aspects of the serverless api. Previously the api requested an array of discord threads, but this design was not ideal for the way the frontend was designed to query. This was changed to query a single thread at a time, based on when the user opens the discussion panel ( rather than compiling a list of all possible discussions).  We also add superstruct to validate calls and results between the frontend and the serverless api. 
Several parsers were added to make mentions, links and attachments work somewhat more nicely. 
There is still a lot of refinements we can make on this. …

feat: wire up discord api to discusstion panel

---

components/Header/Header.tsx
components/Panel/StakeUnstakePanel/Stake.tsx
components/Votes/Votes.tsx
contexts/DelegationContext.tsx
contexts/StakingContext.tsx
contexts/UserContext.tsx
contexts/VotesContext.tsx
hooks/queries/rewards/useOutstandingRewards.ts
hooks/queries/rewards/useRewardsCalculationInputs.ts
hooks/queries/staking/useStakedBalance.ts
hooks/queries/staking/useStakerDetails.ts
hooks/queries/staking/useUnstakedBalance.ts
hooks/queries/user/useUserVotingAndStakingDetails.ts

The current version does not work correctly when logged in as a delegate. Much of the data should originate from the delegator:
1. stake/unstake balances 
2. vote history
3. claimable tokens
This allows many contexts to set an override user address, in this case we can override to the "delegator" address. This happens automatically at the top level ( in header component) when its detected that you are a delegate. Many hooks have now an optional field to override the address, and contexts selectively do this when you set an override address. This fixes the issue without major changes to the code, and keeps it backwards compatible to lower risk of regressions.

fix: fix delegate queries to use delegator address

---

components/Votes/Votes.tsx
components/VotesList/VotesListItem.tsx
web3/queries/votes/getEncryptedVotes.ts

Previously when values were committed, it wasnt clear if we were changing them to be committed again.
This adds a button to reset inputs back to a previously committed vote, and lets you know if you are changing a previously committed value. Otherwise it does not change functionality

feat: add commit reset and dirty flag on input

---

contexts/StakingContext.tsx
hooks/mutations/rewards/useWithdrawAndRestake.ts
hooks/mutations/rewards/useWithdrawRewards.ts
hooks/queries/rewards/useRewardsCalculationInputs.ts
types/staking.ts
web3/queries/rewards/getRewardsCalculationInputs.ts

The amount to claim does not go to 0 after claiming rewards, seems to require a reload or takes a long time to reflect new value after tx is mined.
this was caused by a race condition, where claims are being regenerated on a timer based on contract information. resetting this calculated value to 0 would be quickly reset by the timer since the contract value has not been updated yet.  rather than resetting the final value to 0 when the claim tx succeeds, we change the cached value of the outstanding rewards from the contract call to 0, which is the key value in calculating our claim amount and wont immediately be overridden by the timer.

fix: ensure claim balance goes to 0 after claiming

---

components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx

for staking, when approving an amount less than unlimited, the input box would be cleared. this seemed counter intuitive since that amount should  be the amount you want to stake in the next step.
this only clears input box if you have set "unlimited approval" since that will cause the app to crash if not cleared out. this also disables the approval button while approval is in progress.

fix: prevent clearing stake input if not maxing approval

---

contexts/VotesContext.tsx
hooks/queries/votes/useDecryptedVotes.ts
hooks/queries/votes/useEncryptedVotes.ts
web3/queries/votes/getEncryptedVotes.ts

When committing a vote, letting it roll to next round, the previous commit value keeps showing up as the default in the commit input box. The previous commit is not related to the next round when a vote is rolled, so it should be blank.
This was caused by not filtering decrypted votes by round id when doing a lookup for the committed value, this was treating past votes the same as votes in the current round. we slightly change queries to allow for a round id. this affected past votes, since they  were sharing the same data structure, so a new query is made for all past votes.

fix: filter past commit value from showing in a rolled vote

---

components/Panel/VotePanel/Result.tsx
components/VotesList/VotesListItem.tsx
graph/queries/getPastVotes.ts
helpers/voting/makePriceRequestsByKey.ts
stories/BaseComponents/navigation/Panel.stories.tsx
stories/mocks/votes.ts
types/voting.ts

There were a couple issues, when viewing the zelensky vote, the app would crash due to magic number breaking display formatting. once that was fixed, it would show 2 no values, because the magic number value on the vote was not matching the value on the option, this ended up showing 2 no values rather than yes, no, early vote.
the root cause of this problem was pulling the correct vote number from the subgraph and immediately converting it to a number, this ends up converting the magic number to something that cannot be converted back to the original number.  to fix this we stop tryign to convert votes into numbers and leave them as raw strings. when the number is finally displayed its converted to the correct decimals. 
go to page 2 of past votes, and see the zelensky time magazine vote. …

fix: fix magic number crash and display

---

graph/queries/getGlobals.ts
graph/queries/getPastVotes.ts
graph/queries/getUserVotingAndStakingDetails.ts
helpers/config.ts
hooks/queries/rewards/useGlobals.ts
hooks/queries/user/useUserVotingAndStakingDetails.ts
hooks/queries/votes/useContentfulData.ts
hooks/queries/votes/usePastVotes.ts

We want to be able to run the app in the absense of contentful or the graph. The app should fail gracefully if either app is configured to not include these, or these endpoints fail to return data. 
The app can now be explicitly configured to not include these services by making their environment variable configurations optional.  By disabling these we no longer have access to certain features such as apy calculations, or past vote history, but the app stays stable.  If these endpoints error or timeout the app will report the errors to the user but still work.

fix: allow app to work without graph or contentful

---

components/Panel/VotePanel/Details.tsx
pages/api/_common.ts
pages/api/augment-request.ts
types/voting.ts
web3/queries/votes/getAugmentedVoteData.ts

Consistently getting errors in the serverless function due to large event queries, this is preventing data from being returned from the augment request calls. 
The initial solution was to add a way to configure block start times for each event query, but the way the types and code was structured it was quite difficult to get typescript to approve.  used this as an opportunity to improve the code:
1. optional block start times per contract per chain are added, currently defaulting to 0
2. less casting, stronger type checks generally
3. data parameters sent to serverless function is now validated with superstruct before use
4. an optional parameter for chain id is now available to the caller, rather than hard coding this to 1 ( defaults to 1 if omitted)
5. data returned from serverless …

improve: allow augment request to configure fromblocks

---

components/Votes/Votes.tsx
components/VotesList/VotesListItem.tsx

turns out when you have a delegate/delegator relationship, and both commit 1 vote, you can no longer commit again for any votes you have not already committed. 
This fixes the logic disabling the commit button incorrectly, the logic is a bit tricky, but it seems to work now. also used this as an opportunity to clarify labels when votes are committed from delegate/delegator account. probably should have put this in a new PR but we can see the changes here:
commit cycle where delegator committed viewing from delegate:
reveal cycle from various viewpoints, and a reveal

fix: fixed blocked commits, and delegate/delegator statuses

---

components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
components/Panel/StakeUnstakePanel/Unstake.tsx

if your delegator unstakes, and has pending unstake, only that account can claim it. the delegate should not see that there is pending unstaked tokens.
this hides the pending unstake if you are a delegate
delegate view ( account 8):
delegator view (account 3):

fix: hide unstake as delegate

---

constant/web3/supportedChains.ts
pages/api/_common.ts
pages/api/augment-request.ts
types/voting.ts

We dont want to special case the testnet if we dont have to, doing this has also caused typescript issues when trying to find names for supported chains when using goerli, as that object did not have a goerli id.  
this simply adds goerli into supported chain object and supported chain type, and removes references to the type with goerli.
**do not merge until #153 goes in, the base needs to be set to master**

improve: remove references to goerli as a supported chain, include it natively

---

components/HowItWorks/HowItWorks.tsx

we want a delegate to know that its not thier tokens being staked, but the delegators in the "how it works" section.
this changes the wording slightly to show its the delegators uma at stake, and links to the wallet connect page to see your delegator. 
@ryanwolhuter there is supposed to be a tooltip here, but i cant seeem to get it working, let me know how i can fix

improve: change wording for delegate staking amount

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/OoTypeIcon.tsx
constant/web3/supportedChains.ts

we are labeling links as "DVM requests" but then linking to the OO transaction, this seems incorrect. There should probably be 2 links, 1 for the dvm and 1 for the OO ( if its available).
This fixes the link to dvm so it correctly is based on the dvm price request event transaction. Then adds an optional second link which is based on the OO request event, which may or may not exist for a request.
before:
after:

fix: corrected dvm links in details

---

components/Header/Header.tsx
components/IconWrapper/IconWrapper.tsx
components/Votes/Votes.tsx

Adds a "recent past votes" section to the bottom of the vote page, with a link to see them all at `/past-votes`.

feat: add recent past votes to vote page

---

components/VotesList/VotesListItem.tsx
graph/queries/getPastVotes.ts
helpers/voting/makePriceRequestsByKey.ts
pages/api/augment-request.ts
stories/mocks/votes.ts
types/voting.ts
web3/queries/votes/getActiveVotes.ts

new contract keeps track of roll count, so we dont need to do this bsaed on the augmented data api call
this uses the rollcount number returned from get active requests

improve: move roll logic out of severless

---

components/Panel/VotePanel/VotePanel.tsx
components/VoteHistoryTable/VoteHistoryTableRow.tsx
components/VotesList/VotesListItem.tsx
graph/queries/getPastVotes.ts
helpers/voting/makePriceRequestsByKey.ts
types/voting.ts

vote numbers are only available on resolved requests. its now known as `resolvedPriceRequestIndex`
this uses `resolvedPriceRequestIndex` when its available

fix: show resolved vote numbers in details page

---

components/VotesList/VotesListItem.tsx
contexts/VotesContext.tsx
hooks/queries/votes/useRevealedVotes.ts

the ui would not show delegates who commmitted and revealed
this fixes it so it correctly detects when a delegate has revealed by using the delegators address when querying for revealed events.  this also should show you when logged in as a delegate or delegator if your sibling address has revealed

fix: fix revealed issue for delegate

---

components/Votes/Votes.tsx
helpers/voting/formatVotes.ts
types/voting.ts

Voting contracts have changed their api with regard to commit reveal for delgatees, we want to fix that
this only changes the logic around committing as a delegatee. they now commit based on delegators address in the commit hash. this is enough to get the functions working correctly again.

feat: fix commit/reveal for delegatee

---

components/Panel/MenuPanel/MenuPanel.tsx
components/pages/WalletSettings/PendingRequests.tsx
helpers/config.ts

links to address were being incorrectly formatted inside panel when notifying of a pending delegate request
we did not have a function for configuring address links in the config, were incorrectly using the transaction link generator. this adds an address link generator for each chain.

fix: address link for delegate

---

components/pages/WalletSettings/ConnectedWallet.tsx

copy was wrong when logged in as a delegate in wallet settings
corrrectly switch between copy given delegate/delegator setting

fix: copy around connected wallet delegate

---

pages/api/decode-admin.ts

Defaulting to null in the `transactionSets` map and then attempting to map those results leads to an error.
* Filter null results from the `transactionSets`

fix: filter null results in decode admin

---

components/Dropdown/Dropdown.tsx
components/Input/Input.tsx

Vote text inputs and dropdowns need a minimum width set in addition to their existing maximum width so that they do not squash their content on smaller screens.
Add minimum width to vote dropdown and text input

fix: add width constraints to input and dropdown

---

components/Votes/Votes.tsx

The "Why do I need to sign?" text was incorrectly aligned, and also missing in the commit phase.
* Add sign info text in commit phase
* Move sign info text out of buttons wrapper so that it sits above the buttons

fix: sign info text alignment

---

components/Votes/Votes.tsx
stories/Pages/VotePage/VotePage.stories.tsx

* Make the margin between the title and votes table the same for both the top and bottom tables in upcoming votes.

fix: inconsistent spacing in upcoming votes

---

components/Panel/VotePanel/Details.tsx

* Change font size in decoded admin transactions code blocks (`<pre>` tags) to be 12px.

fix: reduce code font size in decoded admin transactions

---

hooks/queries/rewards/useRewardsCalculationInputs.ts
web3/queries/rewards/getRewardsCalculationInputs.ts

when claiming rewards on a quickly accumulating account, we would see actual claim amounts inconsistent with the amount shown on UI. this would sometimes under or overestimate rewards by a large margin.
In order to calculate the estimated rewards in real time, we need to know the current state of rewards on chain at a specific timestamp, and we need the length of time which has elapsed since that was fetched.  we were not fetching the current block timestamp when querying the data, but rather using "date.now".  this could cause wildly different "fetch times" since block time and date.now can be way off.  as a result estimations could be off by a large amout.  We change this to fetch the block timestamp when we fetch the reward data. This seems to give more consistent estimations, after 5 …

fix: fix reward estimation

---

components/Panel/VotePanel/Result.tsx
components/VotesList/VotesListItem.tsx
constant/voting/earlyRequestMagicNumber.ts

we have a magic number, which is really long, and represents a vote of "too early" for a yes or no query.  if the ancillary data of the request does not include this specifically as an option, we dont convert the number to the label "too early" since we cant find that as an option. this leaves us to show this really long number in the ui.
we now treat the magic number as a unique thing, regardless of the vote type, or if its found in options. This assumes that it will only ever be used to represent "too early". this allows us to decode the number in the UI and show "too early" in place of the number even if its not included in ancillary data. we can easily undo this change if needed. 
previously these would show magic number

fix: handle magic number more robustly

---

components/Panel/StakeUnstakePanel/Stake.tsx

The date-fns library assumes that if you pass in a value to format as an interval with a unit like `{ seconds: value }` then you want the output to be in that unit, i.e. seconds in this case. Passing it in as an interval tells date-fns to format it with the least values instead like x days y hours z minutes etc.
* Pass `unstakeCoolDown` to date-fns `format` as an interval

fix: unstake cooldown always shown as seconds

---

components/GlobalStyle/GlobalStyle.ts

Having `width: 100%` on the body is redundant, and it causes the panel to do this weird jumping thing when it opens. Adding this was a mistake and removing it fixes this issue.
* Remove 100% width on body from `GlobalStyle`

fix: remove global 100% width

---

components/Panel/ClaimPanel.tsx
components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/Unstake.tsx

we are showing unecessary information when logged in as delegate, we want to remove that information.
this deletes certain elements when logged in as delegator for claim panel, stake, and unstake panels.

feat: clean up delegate view for disabled features

---

components/Header/Header.tsx

We currently show the user they are delegate, but not delegator. We should show both
this just enables the same type of notification if the user is curently a delegator, identical in style to the delegate

feat: add notification that user is delegator

---

components/ErrorBanner/ErrorBanner.tsx
components/Wallet/Wallet.tsx
contexts/WalletContext.tsx
hooks/queries/delegation/useCommittedVotesForDelegator.ts
hooks/queries/delegation/useDelegateToStaker.ts
hooks/queries/delegation/useDelegatorSetEventsForDelegate.ts
hooks/queries/delegation/useDelegatorSetEventsForDelegator.ts
hooks/queries/delegation/useIgnoredRequestToBeDelegateAddresses.ts
hooks/queries/delegation/useNewReceivedRequestsToBeDelegate.ts
hooks/queries/delegation/useReceivedRequestsToBeDelegate.ts
hooks/queries/delegation/useSentRequestsToBeDelegate.ts
hooks/queries/delegation/useVoterFromDelegate.ts
hooks/queries/rewards/useIsOldDesignatedVotingAccount.ts
hooks/queries/rewards/useOutstandingRewards.ts
hooks/queries/rewards/useRewardsCalculationInputs.ts
hooks/queries/rewards/useV1Rewards.ts
hooks/queries/staking/useDelegatorStakedBalance.ts
hooks/queries/staking/useStakedBalance.ts
hooks/queries/staking/useStakerDetails.ts
hooks/queries/staking/useTokenAllowance.ts
hooks/queries/staking/useUnstakedBalance.ts
hooks/queries/user/useUserVotingAndStakingDetails.ts
hooks/queries/votes/useActiveVotes.ts
hooks/queries/votes/useCommittedVotes.ts
hooks/queries/votes/useCommittedVotesByCaller.ts
hooks/queries/votes/useDecryptedVotes.ts
hooks/queries/votes/useEncryptedVotes.ts
hooks/queries/votes/useRevealedVotes.ts

Having the wrong chain logic tied up with the general error handling logic was causing some issues. When you connect with the wrong chain, the app would flash the "wrong chain" message and then quickly remove it. The app would then show an "error fetching data" message instead. 
Since being connected to the wrong chain is a special situation that makes it so that no user dependent data has meaning and no actions can be taken, I've elected to move the logic for handling this situation out of the `ErrorContext`. Instead, we add a property to the `WalletContext` called `isWrongChain` which we can use to show/hide a special error banner. This error banner looks the same as the others but is different in that it does not have a "close" button — the only way to get rid of this error is to …

fix: handle wrong chain

---

components/Pagination/Pagination.tsx
stories/Pages/VotePage/VotePage.stories.tsx

The original pagination logic tried to account for fitting in buttons into a space where less than the default number would fit. This is actually pointless because that would only happen on a screen less than 200px wide, which is not a type of device that exists. This logic was overly complicated and caused a bug where the number of buttons and whether to show a "go to first page" button was calculated wrong. This PR removes the complicated logic and fixes the math mistake.
* Remove dependency on screen width in number of buttons calculation
* use `>` instead of `>=`  for `hasMorePagesThanButtons`
* Account for `numberOfPages === defaultNumberOfButtons + 1` when calculating number of buttons

fix: pagination showing 2 1s

---

components/HowItWorks/HowItWorks.tsx
components/Tooltip/Tooltip.tsx

Formatting of this tooltip looked a bit off. Remove a redundant line of css that fixes this weird hyphenation (was a mistake to add it in the first place).
Also changed the label type to `ReactNode` so that we can pass in content in `<strong>` tags so that it can be made bold.
**To test:** connect with **Account 8** on **Goerli**
before:
after:
* remove redundant hyphens
* slightly increase tooltip max width
* allow `ReactNode` as tooltip label
* add strong tag font weight
* make tooltip title bold

fix: delegate address tooltip formatting

---

components/VoteHistoryTable/VoteHistoryTableRow.tsx

In the vote history panel, we show the value "0" as green, which is confusing. We also have several occurrences of "-0" because of rounding. We can fix this by removing the "-" when we encounter "-0" after formatting. 
Old 
New
* Remove negative sign from negative zero
* Show zero as black color

fix: handle 0 and -0 slash amounts

---

graph/queries/getGlobals.ts
helpers/config.ts

we want to override the apr of 0 to something more reasonable
this sets an env to override, remove env to reset back to dynamic calc.

feat: add apr override

---

components/HowItWorks/HowItWorks.tsx

We're applying bottom margin to each of the divs that contain the `InfoBar` components to make space between them. To do this we're targeting divs with the child selector (just a blank space in the css). This selector grabs _all_ divs down the cascade, which means that it also applies the margin to the divs that wrap the action buttons - not what we want. Instead we should use the direct child selector `>` which applies only to the _immediate_ child divs in the cascade.
Before:
After:
* Use `>` instead of ` ` selector to grab only direct child divs

fix: remove unintended bottom margin from button wrapper

---

contexts/UserContext.tsx
contexts/VotesContext.tsx
graph/queries/getPastVotes.ts
helpers/config.ts
helpers/voting/makePriceRequestsByKey.ts
helpers/web3/wallet.ts
hooks/index.ts
hooks/queries/user/useDesignatedVotingV1Address.ts
stories/mocks/votes.ts
types/queries.ts
types/voting.ts
web3/contracts/createDesignatedVotingFactoryV1Instance.ts
web3/index.ts

We currently arent able to decode historical votes made from the v1 contract.
This switches the app to defer to the graphs reveal values when looking up past votes, but maintains the onchain decription for active votes. This automatically looks up desinated voting factory address, but we can override if needed with env var.  btw, i realize now theres a serverless function for this, could switch to that if desired.

feat: use graph for revealing past votes

---

contexts/VotesContext.tsx
web3/queries/votes/getEncryptedVotes.ts

people are seeing decrypt error on active votes
this is happenign because we were not correctly removing v1 encrypted past votes, causing decrypt error during our decryption query

fix: stop showing incorrect decrypt errors

---

constant/voting/voteTiming.ts
helpers/config.ts

phase length differs by primary chain ( goerli shorter than mainnet), this should be configurable
this adds an env to allow phase length to be set in seconds NEXT_PUBLIC_PHASE_LENGTH.  if not specified it wil default to mainnet length.  env has been updated for goerli at a value of 600

feat: make phase length configurable

---

components/Panel/ClaimPanel.tsx
components/Panel/ClaimV1Panel.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx
components/Votes/Votes.tsx
components/Wallet/Wallet.tsx
contexts/ContractsContext.tsx
contexts/DelegationContext.tsx
hooks/queries/staking/useTokenAllowance.ts

we are seeing some weird behavior when fetching data from providers. it turns out we are using the metmask provider once we connect wallet to pull data.
previouslly we had a single instance of a voting and voting token contract which was tied to the wallets provider and signer.  now we have 2 instances, one for reading, using our own provider, and one for writing using the wallets signer. this should make quering more predictable and have less errors, hopefully improving usability for people who are having connectivity issues.

 fix: use non wallet provider for reading data 

---

components/VoteTimeline/CommitPhase.tsx

people are seeing commit in xx hours, during a reveal phase, this is confusing becuase commit phase is over
we were assuming there were only 2 states to the active vote banner for commits, "commit phase starting in xx" and "time remaining to commit". added a third state, "commit phase over", which only shows during active reveal phase.

fix: let user know commit is over if in reveal phase

---

helpers/voting/polymarket.ts

people are having a hard time selecting correct options when selecting polymarket votes, and we arent able to detect the options
this uses a regex to match the p1,p2,p3 values, which only works in the case where there are those 3 options, and builds up options list based on matches. it will also always append magic number ( too early ) and a custom input
This will only display if its able to find at least 3 options.

feat: add dynamic polymarket dropdown parsing

---

hooks/queries/votes/useRevealedVotes.ts
web3/queries/votes/getRevealedVotes.ts

theres an intermittent problem people are reporting, where they reveal but the app doesnt recognize they reveal.
unfortunately not able to reliably reproduce this problem, but it may be due to out of sync providers. when we write the reveal, we use the wallets signer, but when we read if we have revealed we use an infura provider, its possible these are sometimes out of sync.  this will cause problems with react query overwriting an empty revealed query after we have updated that cache locally when we know our tx revealed.  this change tries to merge the revealed table when a query to web3 is done to not blow away any locally modified values.

fix: merge revealed queries with existing cache

---

graph/queries/getPastVotes.ts

The v1 past votes subgraph is often quite slow, and this would be made much worse by increasing the number of entries requested from the default 100 to the actual 309.
My question is this: why are we even querying this from the graph every time in the first place? We know the results for v1 will never change. At first I thought perhaps we should put this logic behind a serverless function and cache the result, but why even make it that complicated?
In this solution, I've simply downloaded the result of this query and saved it as a json file. I've replaced the fetching logic with code that asynchronously downloads this json file with a dynamic import. This way our processing logic does not need to be affected, i.e. if we decide to add or remove parsing logic in the future we can do so …

improve: use json file for past votes v1

---

helpers/voting/getVoteMetaData.ts

we wanted a quick fix for an upcoming vote coming from oracle v3
this hard codes the description for the assertion, it assumes we are not going to get anymore v3 disputes, and that we will generalize this soon

feat: add hard coded assertion vote

---

components/GlobalStyle/GlobalStyle.ts

qr codes are not being rendered correctly
there was a global style causing edges to be rounded for svgs, this was removed

fix: remove svg global styling affecting qr codes

---

hooks/mutations/rewards/useWithdrawAndRestake.ts
hooks/mutations/rewards/useWithdrawRewards.ts
types/staking.ts

it seems like sometimes especially on mobile, when we claim and stake the amount to claim doesnt zero out as expected
difficult to repro on desktop, but it looks like we were trying to reset outstanding rewards on a defunct key, so updated the reset to the correct rq key.

fix: set rewards to 0 on claim and withdraw

---

hooks/queries/rewards/useIsOldDesignatedVotingAccount.ts
hooks/queries/rewards/useV1Rewards.ts
hooks/queries/staking/useDelegatorStakedBalance.ts
hooks/queries/staking/useStakedBalance.ts
hooks/queries/staking/useUnstakeCoolDown.ts

errors are flashing, unable to be read when on main page, such as cancelling a tx
this removes the clear errors from react query queries, these tend to run frequently, particularly when re-focusing on page.  this means error banner sticks around until user manually closes it. 
future work - may need to have some kind of global error manager to clear errors after some seconds

feat: remove error clearing from rq queries

---

.storybook/preview.tsx
stories/BaseComponents/info/CooldownTimer.stories.tsx
stories/BaseComponents/navigation/Panel.stories.tsx
stories/Pages/PastVotesPage.stories.tsx
stories/Pages/VotePage/VotePage.stories.tsx
stories/mocks/misc.ts
stories/mocks/votes.ts

We have some story code that uses `Math.random` and `new Date`. These are different on every push to chromatic, creating false positives in the visual regression tests.
Remove these usages in favor of deterministic values.

fix: remove non deterministic values from mocks

---

components/Input/EmailInput.tsx
components/Panel/RemindMePanel/RemindMePanel.tsx
helpers/config.ts

when signing up for reminders, we want to add mailchimp tags to specify they are a "voter"
this required adding an additional property "tags" which needs to be passed in as a env var. the value of the env is not a human string, but a tag id which you can copy from a hidden var when you generate a mailchimp form. this has been added to the vercel deployments. 
this also will show errors coming from mailchimp now, previously we were not.

fix: add tags to new email reminders

---

components/HowItWorks/HowItWorks.tsx

how it works values can take a long time to load
we we only displaying any values once all values were available, this would block showing values which may have loaded already, but were blocked from showing until everything loaded.  this changes it so that the values are displayed only when their direct depenencies are loaded.

improve: allow howitworks values to show as they load

---

components/VoteList/VoteListItem.tsx
constant/query/queryKeys.ts
contexts/VotesContext.tsx
graph/index.ts
graph/queries/getActiveVoteResults.ts
hooks/index.ts
hooks/queries/votes/index.ts
hooks/queries/votes/useActiveVoteResults.ts

we want to see vote information during reveal
in order to do this, we need to query the graph for active votes.  this will attach the "results" and "participation" data needed for each active request, and this data will automatically populate the results panel.  theres a known issue, that if the vote rolls the results and participation will not clear, but we dont experience rolls on mainnet, so its not a critical bug.  the graph will need to be updated to resolve this.

feat: add vote stats during reveal

---

web3/queries/delegation/getDelegateToStaker.ts
web3/queries/rewards/getOutstandingRewards.ts
web3/queries/votes/getEncryptedVotes.ts

We did not include cases for when there is no address in two of our queries. 
For the encrypted votes query, this caused us to query all of the encrypted vote events instead of just for a specific address. We did not notice this error when we tested on goerli because the events we were looking for were still present. This was an error on mainnet because the query returned more than 10000 events, which causes infura to throw an error.

fix: return empty when no address

---

components/HowItWorks/HowItWorks.tsx
components/Panel/ClaimPanel.tsx
contexts/DelegationContext.tsx

rewards are not being updated in dynamically
there was logic lost in refactor that dynamically calculates staked values. this needs to be based on the delegate or the logged in account. re-added this logic.

fix: dynamic reward calculations

---

components/Panel/StakeUnstakePanel/Stake.tsx
components/Panel/StakeUnstakePanel/StakeUnstakePanel.tsx

when wallet not connected, there was a way to enable the stake button by messing with the input box. this leads to errors on the app.
this makes sure we know to disable the staking inputbox and other buttons when no wallet is connected.

fix: disable staking max button with no wallet connected

---

pages/api/discord-thread.ts
types/voting.ts

- Fix the link to the discord threads by using the `message.thread.name` instead of `message.content`. 
- Explanation: In some cases when editing the thread title after creation, `message.content` returned by discord API still returns the old title but `message.thread.name` is up to date. That's why we always need to use `message.thread.name`

fix: discord evidence rationale link

---

helpers/voting/polymarket.ts

Polymarket changed their ancillary data. We need to update the parsing regex to allow this.

fix: add "." to polymarket dropdown regex

---

contexts/VotesContext.tsx
web3/queries/votes/getEncryptedVotes.ts

There is a bug where the app does not recognize that a rolled vote is a new vote. it repopulates the form field with the user's encrypted vote from the previous round. 
We want the vote to be treated as a new vote. In my opinion it does not make sense to automatically assume that the user wants to vote the same as the previous time for a rolled vote anyway, since by the nature of a rolled vote it is likely that the user has changed their mind. At the very least they should consider their new vote before committing.
To fix this behavior we should filter encrypted votes by round id.

fix: make user re-select their vote when a vote rolls

---

components/Panel/VotePanel/Result.tsx

sometimes it's interesting to follow the voter numbers to gauge approx votes revealed vs. remaining, but my brain short circuits when I try to parse long numbers without a separator.
ethers has a helper called [commify()](https://docs.ethers.org/v5/single-page/#/v5/api/utils/display-logic/-%23-utils-commify) to do this automagically - could that be an easy way to format it?What's the reason for the improvement?
commify the 2 places where we display this in vote results

improve: commify uma large displays of tokens in vote results

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/VotePanel.tsx
helpers/voting/getVoteMetaData.ts
pages/api/augment-request.ts
types/voting.ts
web3/queries/votes/getAugmentedVoteData.ts

we arent correctly detecting osnap assertions, and not showing relevant data
1. this makes it so we correctly detect assertions ( we were looking for a string that doesnt exist on these osnap assertions )
2. we decode the claim now in details
3. we have the correct options, previously the options were missing, so votes should be woking
with more time we need to fix showing the correct title, and parsing the claim data similar to OO.

improve: improve osnap vote rendering

---

graph/queries/getPastVotes.ts
helpers/util/fetchAllDocuments.ts

thegraph server only returns 1000 documents at a time and does not support standard PageInfo features like cursors for pagination. So we might get into a situation where we think we are fetching all documents but we're only fetching this first 1000. 
It seems unlikely that we'll ever have more than 1000 upcoming votes so I'm only implementing this logic for `pastVotes`
In this solution all we're doing is fetching 1000 at a time until we get less that 1000 then we know we've got them all. 
closes #UMA-2125

feat: ensure we fetch all past votes

---

web3/contracts/createOOV3ContractInstances.ts

theres a code smell where we are initializing providers with potentially undefined data
this removes boba which we no longer support and filters out provider urls that are undefined before creating instances

improve: remove unused chain, disable creating providers if no envs supplied

---

components/VoteList/VoteList.tsx
components/VoteList/VoteListItem.tsx
components/VoteList/VoteTableRow.tsx

We want to use CSS to truncate text if it spans more than 2 lines. We think 2 lines is more than enough space for a title, but in the rare case that it is larger we don't want to break the layout.
closes UMA-2311

clamp lines to 2 in vote list titles

---

components/VoteList/VoteListItem.tsx

##motivation
Some inconsistent spacing in cote status labels.

fix spacing for vote status

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/VotePanel.tsx

title and claim data is not showing up correctly for current vote
augmented data does not seem to be loading, so use the hook useAssertionClaim instead to fetch claim data. this seems to resolve the issues.

fix: load claim data through hook which is more reliable

---

helpers/voting/getVoteMetaData.ts

non polymarket yes or no query not showing drop down options for voting
this attempts to parse options from ancillary data in polymarket style, but not attribute it to a polymarket vote

fix: parse yes_no query options

---

web3/contracts/createOOV3ContractInstances.ts

The app was not correctly filtering out config items where the rpc URL is undefined and the ethers will attempt to connect to `localhost:8545` if none is provided, hence the errors in console.
The fix is pretty simple, we were not coercing the value to a boolean, we were creating a Boolean _object_ which will always be truthy.

correctly coerce to boolean when filtering rpcUrls

---

helpers/config.ts
hooks/queries/votes/useOptimisticGovernorData.ts

With the deprecation of hosted subgraph service we need to migrate to Subgraph Studio
Fixes: https://linear.app/uma/issue/UMA-2640/subgraph-studio-in-voter-dapp

fix: migrate to graph studio

---

contexts/DelegationContext.tsx

1. Connect delegate wallet, should have some outstanding rewards
2. Disconnect wallet => outstanding rewards should read `0`
3. Connect delegate wallet again (outstanding rewards should appear again) then switch to non-delegate wallet, outstanding rewards should now read `0`

reset outstanding rewards if no delegate wallet connected

---

components/Panel/VotePanel/Result.tsx
graph/queries/getActiveVoteResults.ts
graph/queries/getPastVotes.ts
helpers/voting/makePriceRequestsByKey.ts
stories/BaseComponents/navigation/Panel.stories.tsx
types/queries.ts
types/voting.ts

Some users have noticed it is a bit unclear how many users have committed or revealed since the UI previously only shows amount of **votes**. 
Now we show how many tokens committed and revealed. we also show the percentage of users that revealed.

feat: improve wording around commited/revealed votes

---

components/Panel/VotePanel/Details.tsx
contexts/VotesContext.tsx
hooks/queries/votes/useAugmentedVoteData.ts
package.json
pages/api/_common.ts
pages/api/augment-request-gql.ts
pages/api/augment-request.ts
stories/mocks/votes.ts
types/voting.ts
web3/queries/votes/getAugmentedVoteData.ts
yarn.lock

augment request which is responsible for finding metadata about transactions has been failing
This updates augment request to use the graph and to only query for a single request as its displayed, this speeds up calls, improves caching, and hopefully stops erroring and timing out
oracle v3:
oracle v2:
skinny oo:

fix: use the graph for augmented data

---

components/Panel/VotePanel/Result.tsx
graph/queries/getActiveVoteResults.ts
graph/queries/getPastVotes.ts
types/queries.ts

Since updates to the subgraph [here](https://github.com/UMAprotocol/subgraphs/pull/80), we are tracking the tokens staked by each committer, when they commit their vote. We now use this value to calculate the percentage of tokens that revealed.

use new committed tokens counter from graph

---

web3/queries/delegation/getDelegateSetEvents.ts

that has been report that accounts cannot accept delegate request
narrowed this down to a call which picks a single request out of all the delegate requests an address was sent.  previously taking the oldest, now taking the newest request.

fix: fix accepting delegate when changing delgated wallet

---

graph/queries/getActiveVoteResults.ts

We are only ever seeing max 100 commit addresses
apparently gql query limits you to 100 returned values, so we increased the limit, which should hold us over for a while

fix: increase subgraph query limits for commits and reveals

---

pages/_app.tsx
pages/_document.tsx

- places the tracker in the correct component as per [docs](https://nextjs.org/docs/pages/building-your-application/optimizing/third-party-libraries#google-analytics)

fix: place GA tracker in correct component

---

graph/queries/getPastVotes.ts

some users are being told they didnt participate in a past vote when they did.  did not affect rewards, only shows wrong information in ui
This was caused by having over 100 voters, and gql by default limits array queries to 100, unless specified. This means some revealed vote data was being cutoff, and this would affect voters somewhat randomly.  This increases array limit on revealed votes and others to 100, which gives us a lot more room to grow.  we are around 110 voters or so

fix: fix issue with some voters not showing they voted in past votes

---

pages/api/discord-thread.ts

this discussion is missing the first X number of posts `Will Israel invade Lebanon in September?`
the discord api returns posts in reverse order, ie newest first. and theres a limit on number of messages that get returned. we can modify this to a max of 100, which fixes the issue for now, but we need to spend more time to add pagination to this call.
you can see in discussion tab in this pr DOMAH is first which matches discussion in discord evidence rationale
vs the prod app it shows someone else

fix: increase message query size

---

hooks/queries/votes/useVoteDiscussion.ts
package.json
pages/api/discord-thread.ts
web3/queries/votes/getVoteDiscussion.ts
yarn.lock

we just fixed pagin in discord, now discussion is loading forever due to rate limiting
- do not paginate thread lookups since there are so many old threads we can discard
- adjusted querying logic to prevent an extra query by ending early if messages returned is less than limit
- added sleep between loops
- next version bumped
- use get vs post to ensure caching working on serverless call
- refresh 20 sec vs on focus

fix: rework paging logic in discord

---

components/VoteHistoryTable/VoteHistoryTableRow.tsx
contexts/VotesContext.tsx

- Fixes the voting history issues
- Depends on the new version of the voting v2 subgraph https://github.com/UMAprotocol/subgraphs/pull/85
Due to TheGraph working memory limitations we need to show a "pending" chip for recent past votes earnings. These are updated once the voter interacts with the contract.

fix: voting history

---

components/Panel/VotePanel/VotePanel.tsx
hooks/queries/votes/useVoteDiscussion.ts
pages/api/discord-thread.ts
types/voting.ts
web3/queries/votes/getVoteDiscussion.ts

Currently we only use the Identifier and timestamp to fetch the associated thread from discord.
In this PR we also use the title to find the thread.

use title and timestamp to index discord threads

---

components/Panel/VotePanel/Details.tsx
helpers/voting/projects/polymarket.ts
hooks/queries/votes/usePolymarketLink.ts
pages/api/get-polymarket-link.ts

We strip all tags (childChainId, ooRequester and childRequester) from DVM ancillary data, leaving only original ancillary data + initializer. we hash this to find the questionId, replicating Polymarket's logic.

sanitize and hash ancillary data for question ID

---

components/Input/TextInput.tsx
hooks/helpers/useHandleDecimalInput.ts

Some mobile browsers set the default decimal separator as a comma instead of a period.
The Fix:
- Attempt to hint at mobile browsers which separator to use.
- Replace commas with periods when input mode is decimal and input type is number

handle comma in decimals

---

components/Modals/MultipleValuesInputModal.tsx
hooks/inputs/useMultipleValuesVote.tsx

- input values set to committed vote values on every render in useEffect, effectively stopping us from updating our vote.
- Set initial input values only once when committed vote is first decrypted. Keep track of this with a ref.

fix: unable to edit committed multiple values vote

---

pages/api/discord-thread/_utils.ts
pages/api/discord-thread/index.ts
types/voting.ts
vercel.json

closes FE-54
1. Set max duration to 5 minutes to prevent timeouts
2. In case of an error after max retries, return a stale response we can cache in redis.

fix: hanging calls to discord-thread 
