pages/api/_common.ts
pages/api/augment-request.ts

previously there were build issues blocking CI. this PR fixes this.

fix build issues

---

components/PanelErrorBanner/PanelErrorBanner.tsx

accidentally merged previous pr to wrong branch
https://github.com/UMAprotocol/voter-dapp-v2/pull/39

fix: errors now fit in panel

---

components/HowItWorks/HowItWorks.tsx

fix: rename voting cycles to votes

---

components/Pagination/Pagination.tsx
components/Panel/HistoryPanel.tsx
components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/Result.tsx
components/VoteTimeline/CommitPhase.tsx
components/VoteTimeline/RevealPhase.tsx
components/VoteTimeline/VoteTimeline.tsx
components/Votes/Votes.tsx
stories/BaseComponents/navigation/Panel.stories.tsx
web3/mutations/votes/commitVotes.ts
web3/mutations/votes/revealVotes.ts

Fixes for several random small presentational bugs. No dapp. logic is changed.

bug: misc mobile bugs 2

---

components/Panel/StakeUnstakePanel/Stake.tsx

Signed-off-by: ryanwolhuter <dev@ryanwolhuter.com>

fix wrong input amount in approve

---

components/Notifications/Notification.tsx

Make the check icon for success notifications green.

improve: make notification check icon green

---

components/Banner/Banner.tsx
components/Button/Button.tsx
components/Header/Header.tsx
components/HowItWorks/HowItWorks.tsx
components/VotesList/VotesList.tsx
components/VotesList/VotesListItem.tsx
components/VotesList/VotesTableHeadings.tsx
components/pages/styles.tsx
stories/Pages/VotePage/VotePage.stories.tsx
stories/mocks/votes.ts

I've added some fancy css that makes the page and the vote table smarter about how it handles spacing. Now it determines how much space items should take in the table and how much padding the page should have based on a combination of our preferred values from the design, the width of the page, and the smallest value that doesn't break the design.

improve: make vote table columns narrower

---

components/pages/PastVotes.tsx
components/pages/Vote.tsx
components/pages/WalletSettings/WalletSettings.tsx
components/pages/styles.tsx

Smaller loading spinner looks more classy.

improve: make main page loading spinner smaller

---

pages/api/decode-admin.ts

Improves decode-admin outputs. example output:

feat: improve admin decoding output

---

package.json
pages/api/_common.ts
yarn.lock

Signed-off-by: chrismaree <christopher.maree@gmail.com>

fix: address issue in hardcoded implementation

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/OoTypeIcon.tsx
helpers/util/misc.ts
types/voting.ts

Show the originating chain tx for votes if it exists and is not ethereum.

improve: add request tx and chain tx to augment

---

graph/queries/getPastVotes.ts

this adds the extra metadata needed to show table and graph of vote participation for v1 voting

feat: add vote metadata to v1 votes

---

pages/api/discord-thread.ts

This function adds a discord serverless function to fetch discord messages from the UMA discord to be rendered within the UMA voterdapp.
endpoint: `/api/discord-thread`
sample payload (that shows 1 request that does not have a discord thread and 2 that do):
```
{
"l1Requests": [
{
"identifier": "0x41646d696e203138320000000000000000000000000000000000000000000000",
"time": 1669239143
},
{
"identifier": "0x4143524f53532d56320000000000000000000000000000000000000000000000",
"time": 1669309955
},
{
"identifier": "0x4143524f53532d56320000000000000000000000000000000000000000000000",
"time": 1669328675
}
]
}
]
}
```
sample response:
```
{
"identifier": "0x41646d696e203138320000000000000000000000000000000000000000000000",
"timestamp": 1669239143,
"thread": []
},
{
"identifier": …
```

feat: add discord serverless function

---

components/VotesList/VotesListItem.tsx

Signed-off-by: ryanwolhuter <dev@ryanwolhuter.com>

fix: add target blank to vote status links

---

components/VotesList/VotesListItem.tsx
components/VotesList/VotesTableHeadings.tsx

The spacing in the table is now responsive based on the table's container size as well as the page size and page padding. We use css variables to set these and update them dynamically as needed. The vote title is now always as long as possible while still keeping the table width consistent.

fix: add even fancier table layout algorithm

---

pages/api/discord-thread.ts

enforce discord API token is added correctly in serverless function.

fix: add process env for DISCORD_TOKEN

---

components/Votes/Votes.tsx
components/Wallet/Wallet.tsx
contexts/UserContext.tsx
contexts/WalletContext.tsx
helpers/index.ts
helpers/voting/formatVotes.ts
helpers/web3/signing.ts
hooks/helpers/useSign.ts
hooks/index.ts
hooks/queries/votes/useDecryptedVotes.ts
pages/_app.tsx

this was accidentally merged to a branch rather than master. just need a quick approval, no review is necessary this was previously approved. no changes were made, other than merge conflicts. see this pr https://github.com/UMAprotocol/voter-dapp-v2/pull/127

improve: add explicit signing button

---

components/HowItWorks/HowItWorks.tsx

Signed-off-by: Pablo Maldonado <pablo@umaproject.org>
Fixes the total number of votes where the user participated in

fix: number to total votes

---

components/Panel/StakeUnstakePanel/Stake.tsx

fix: copy around staking as delegate

---

components/Wallet/Wallet.tsx

when changing the connect button color to red, did not check the color once connected
fixed back to

fix: make sure wallet connected is not red

---

components/Header/Header.tsx

fix: improve delegate wallet copy

---

components/pages/Vote.tsx
graph/index.ts
graph/queries/getGlobals.ts
helpers/util/formatNumber.ts
hooks/index.ts
hooks/queries/rewards/useGlobals.ts
types/staking.ts

previously we hardcoded the apy heading to 30% or something like that. we want to get the dynamic value.
This uses the graph to pull the new value from "global" state.  This was recently updated so that we dont need user information to pull the apy value.  APY is also renamed to APR to match the how to section.

feat: enable real time apr display

---

components/Header/Header.tsx
components/Votes/Votes.tsx
components/VotesList/VotesListItem.tsx
hooks/queries/delegation/useCommittedVotesForDelegator.ts

wanted to remove linter warnings

improve: fix linter warnings

---

.gitignore
cypress.config.ts
cypress/e2e/simple.cy.ts
cypress/fixtures/example.json
cypress/support/commands.ts
cypress/support/e2e.ts
cypress/tsconfig.json
package.json
tsconfig.json
yarn.lock

would be nice to have an e2e test suite to lessen the amount of manual testing required on the app
this basically adds cypress with no other changes, and a couple simple tests as a proof of concept
screenshot of the video produced running `yarn cypress:run`

feat: basic cypress tests

---

components/Panel/StakeUnstakePanel/Unstake.tsx

fix: remove log

---

web3/queries/votes/getActiveVotes.ts

this removed deleted requests from active votes

fix: use getPendingRequestsPostUpdate

---

components/Votes/Votes.tsx

When your delegate/delegator commits, you could potentially change their vote on your account. we wanted to warn the user
This adds a hover info when this behavior is detected

feat: add warning when user changing prev vote from seperate account

---

components/Panel/StakeUnstakePanel/Unstake.tsx

* Apply same duration fix in unstake

fix: also format duration in unstake

---

README.md
components/Panel/MenuPanel/MenuPanel.tsx
components/Panel/PanelFooter.tsx
components/VotesList/VotesListItem.tsx
data/approvedIdentifiersTable.json
pages/api/augment-request.ts
stories/BaseComponents/navigation/Nav.stories.tsx

*Change umaproject.org links to point to uma.xyz instead
* Add a link to projects.uma.xyz in the nav links
* Make the "powered by" in the footer link to uma.xyz

feat: update links

---

components/Panel/DelegationPanel.tsx
components/Panel/HistoryPanel.tsx
components/VotesList/VotesListItem.tsx

we want to fill in missing links

feat: add missing doc links

---

graph/queries/getPastVotes.ts

Swap committVotes.length and revealedVotes.length

fix: swap committed and revealed

---

graph/queries/getPastVotes.ts

Forgot to do this for the v1 past votes query

fix: swap in v1 as well

---

pages/api/augment-request.ts

- wip
- feat: address request augmentation issue with augmented cross-chain events

feat: address request augmentation issue with augmented cross-chain events

---

components/Panel/HistoryPanel.tsx
components/VoteHistoryTable/VoteHistoryTable.tsx

we want to change the wording from score to earnings
afaik this only needs to change in 2 places

improve: change score to earnings

---

pages/api/decode-admin.ts

Signed-off-by: chrismaree <christopher.maree@gmail.com>

feat: enable GovernorV2

---

constant/voting/voteTiming.ts

phase length is wrong for mainnet
change length to correct value

fix: fix phase length for mainnet

---

components/Votes/Votes.tsx

we want to show a limited view of past votes, up to 5. currently we show the entire past votes table on the main page.
this refactors the vote component to separate the logic of "active", "upcoming" and "past" views into their own functions. the "past" view is re-used in both active and upcoming phases, so we have less duplicate code. 
upcoming view
active view
past view

feat: refac vote page to show only 5 past votes

---

components/Pagination/Pagination.tsx
components/Panel/HistoryPanel.tsx
components/Votes/ActiveVotes.tsx
components/Votes/UpcomingVotes.tsx
components/index.ts
components/pages/PastVotes.tsx
components/pages/UpcomingVotes.tsx

Motivation is the same as https://github.com/UMAprotocol/optimistic-oracle-dapp-v2/pull/117

fix: implement pagination fix from oracle

---

graph/queries/constants.ts
graph/queries/getUserVotingAndStakingDetails.ts

- Handles pagination in votes slashed in users query to fetch vote history participation

fix: votes slashed pagination

---

.gitignore

- Ignore all kind of .env files to prevent this files from being pushed

feat: ignore all env files

---

components/VoteList/VoteListItem.tsx

fix: og text overflow

---

pages/api/discord-thread.ts

discord comments are rendered as markdown, its possible to make really large text in comments by using header tag #.  we want to remove this ability
before
after
this uses a regex to identify these headers and turn them bold.  also fix some bold formatting as well

improve: change all headers in discord comments to bold

---

pages/api/augment-request.ts

We arent seeing details for polymarket votes
this puts a limit on how far back events are processed for augmented data. data still takes a long time to load, but it does eventually. will need to look into better caching solutions

fix: limit augment event query lookback

---

helpers/util/misc.ts

this is missing and causing details pane to crash

fix: add base scan link

---

pages/api/augment-request.ts
vercel.json

closes UMA-2556
`augment-request` was timing out preventing users from voting.
here we increase max duration to 5minutes

increase max duration to 5 minutes

---

helpers/voting/polymarket.ts

We have another yes no test request which is not from polymarket but is incorrectly being labeled as such
this adds known polymarket addresses and child chain to label polymarket requests

fix: differentiate polymarket from other yes no queries

---

web3/queries/votes/getCommittedVotes.ts
web3/queries/votes/getCommittedVotesByCaller.ts
web3/queries/votes/getRevealedVotes.ts

unable to reveal due to event errors
add lookback limits on the failing event queries

fix: reduce log lookbacks to fix reveal

---

web3/queries/votes/getAssertionClaim.ts
web3/queries/votes/getEncryptedVotes.ts

there is still a few people unable to reveal, these changes seem to allow them
looks farther back for encoded votes

fix: reduce assertion claim lookback

---

helpers/config.ts
package.json
pages/_document.tsx
yarn.lock

We need to track tis app in GA. pull the same tracking ID from env

add ga tag

---

components/Panel/VotePanel/Result.tsx
components/ProgressBar/ProgressBar.tsx
graph/queries/getActiveVoteResults.ts
graph/queries/getPastVotes.ts
helpers/index.ts
helpers/typeUtilities.ts
helpers/util/formatNumber.ts
helpers/voting/makePriceRequestsByKey.ts
types/queries.ts
types/voting.ts
yarn.lock

It would be nice to see how close we are to reaching quorum on a vote.
We check 2 things here:
1. minimum nominal amount of votes needed.
2. agreement

feat: add quorum progress section

---

web3/queries/votes/getUpcomingVotes.ts

we are missing some upcoming votes
lookback was not far enough, less than 2 days, we change it to about 4 days

fix: look for past votes further back

---

pages/api/discord-thread.ts

batch fetching all discord messages

---

components/Panel/VotePanel/Discussion.tsx
components/Panel/VotePanel/VotePanel.tsx
hooks/queries/votes/useVoteDiscussion.ts
pages/api/discord-thread.ts

add banner if discord api fails

add banner for discord rate limit

---

hooks/queries/votes/usePolymarketData.ts

closes UMA-2826
PM changed the shape of their API response, so we were unable to show a link to the PM market for a particular dispute.

fix for polymarket's new response structure

---

components/AnnouncementBanners/AnnouncementBannerWrapper.tsx
components/AnnouncementBanners/VoteHistoryBanner.tsx
components/Layout/Layout.tsx

add vote history banner

---

components/Layout/Layout.tsx

vote history was fixed
removes banner that warns vote history is not working

improve: remove vote history banner warning

---

helpers/config.ts
web3/contracts/createDesignatedVotingFactoryV1Instance.ts
web3/contracts/createVotingContractInstance.ts
web3/contracts/createVotingTokenContractInstance.ts
web3/contracts/createVotingV1ContractInstance.ts

sepolia vdapp not working right
Fixes some hard coded spots reliant on mainnet, adjusted ENV vars for sepolia deployment

fix: remove hardcoded mainnet contract references

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/VotePanel.tsx
components/VoteList/useVoteListItem.tsx
helpers/index.ts
helpers/voting/getVoteMetaData.ts
helpers/web3/decodeHexString.ts
web3/queries/votes/getAssertionClaim.ts

fix: fix v3 assert truth title and description

---

pages/api/discord-thread.ts

improve: order discord discussion newest to oldest

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/VotePanel.tsx
graph/queries/getPastVotes.ts
helpers/voting/makePriceRequestsByKey.ts
helpers/voting/resolveAncillaryData.ts
stories/mocks/votes.ts
types/voting.ts

renaming the variable from the last fix to something more reasonable, from displayAncillaryData to ancillaryDataL2

improve: rename ancillary data for l2

---

pages/api/discord-thread.ts

temporarily override across v2 title

---

pages/api/discord-thread.ts

Reverts UMAprotocol/voter-dapp-v2#368

Revert "temporarily override across v2 title"

---

graph/queries/getUserVotingAndStakingDetails.ts

- Fixes vote slashing pagination in graph query

fix: pagination in votingv2 graph query

---

pages/api/discord-thread.ts

strip invalid characters from title

---

components/Panel/VotePanel/Discussion.tsx
types/voting.ts

Signed-off-by: Chris Maree <christopher.maree@gmail.com>

Add Reply support to UI

---

components/Panel/VotePanel/Details.tsx
components/Panel/VotePanel/VotePanel.tsx
components/Tabs/Tabs.tsx

⏺ Styling Changes Summary
Tab Component
- Renamed tabs for consistency between AI summary and raw comments
- Improved mobile layout with better spacing and scroll behavior
- Fixed tab memory to prevent showing non-existent tabs when switching vote types
Details Panel
- Simplified Ancillary Data display with collapsible "View Decoded/Raw" buttons
- Made Description section smarter - preserves markdown links and line breaks
- Added identifier as a pill element alongside chain and oracle type
- Improved spacing throughout the modal for better readability

Fix: refine voterdapp styling
